services:
  - type: web
    name: satisfaction-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn satisfaction_project.wsgi"

# a creer dans render.com
#SECRET_KEY
#DEBUG=False
#DATABASE_URL
#ALLOWED_HOSTS