# Generated by Django 6.0.4 on 2026-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id_soummission', models.BigIntegerField(primary_key=True, serialize=False)),
                ('agent_appel', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('consentement_enquete', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_services_utilises', models.IntegerField(blank=True, null=True)),
                ('service_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('frequence_service_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('service_secondaire', models.CharField(blank=True, max_length=255, null=True)),
                ('frequence_service_secondaire', models.CharField(blank=True, max_length=100, null=True)),
                ('accessibilite_service', models.CharField(blank=True, max_length=100, null=True)),
                ('rapidite_service', models.CharField(blank=True, max_length=100, null=True)),
                ('satisfaction_globale', models.CharField(blank=True, max_length=50, null=True)),
                ('qualite_service', models.CharField(blank=True, max_length=50, null=True)),
                ('confiance_service', models.CharField(blank=True, max_length=50, null=True)),
                ('satisfaction_support_client', models.CharField(blank=True, max_length=50, null=True)),
                ('problemes_rencontres', models.TextField(blank=True, null=True)),
                ('propositions_amelioration', models.TextField(blank=True, null=True)),
                ('note_globale', models.FloatField(blank=True, null=True)),
                ('mois_enquete', models.CharField(blank=True, max_length=20, null=True)),
                ('annee_enquete', models.IntegerField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
